# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: ⚠️ Breaking Changes
      labels:
        - 🛠 breaking
    - title: ✨ New Features
      labels:
        - ✨ enhancement
    - title: 🔨 Quality Of Life
        - 🔨 quality-of-life
    - title: 🐛 Bug Fixes
      labels:
        - 🐛 bug
    - title: Other
      labels:
        - "*"
